# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'critical'), (2, 'high'), (3, 'medium'), (4, 'low')], default=1),
        ),
    ]
