# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20170604_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='resolved',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='completed_at',
            new_name='resolved_at',
        ),
    ]
