# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20170604_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
