# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_list_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='name',
        ),
        migrations.AddField(
            model_name='list',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='main_label',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='todo.Label'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='list',
            name='labels',
            field=models.ManyToManyField(blank=True, to='todo.Label'),
        ),
    ]
